apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hiremate-ingress
  namespace: hiremate-prod
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - api.hiremate.ai
    secretName: hiremate-tls-cert
  rules:
  - host: api.hiremate.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hiremate-backend-service
            port:
              number: 5000
