apiVersion: v1
kind: Secret
metadata:
  name: hiremate-secrets
  namespace: hiremate-prod
type: Opaque
stringData:
  JWT_ACCESS_SECRET: "production_jwt_access_secret_key_83921703"
  JWT_REFRESH_SECRET: "production_jwt_refresh_secret_key_92817401"
  NVIDIA_API_KEY: "nvapi-prod-placeholder-key"
